#ifndef DEINFLECTION_RULE_H
#define DEINFLECTION_RULE_H

#define MAX_OUTPUTS 4
typedef struct DeinflectionRule {
    const char *name; // kana_in, but gperf expects the member to be called 'name'
    /* Using s8 would calculate lengths at compile time, but increase binary size */
    const char *kana_out[MAX_OUTPUTS];
    const char *rules_in;
    const char *rules_out;
} DeinflectionRule;

// generated by gperf
struct DeinflectionRule *in_word_set(register const char *str, register size_t len);

#endif // DEINFLECTION_RULE_H
