.TH DICTPOPUP\-CREATE 1
.SH SYNOPSIS
.B dictpopup\-create
[\fILOCATION\fR]...
.SH DESCRIPTION
.B dictpopup\-create
creates a database used by 
.BR dictpopup (1)
from the Yomichan dictionary files in the current directory.
By default, the database is stored in $XDG_DATA_HOME/dictpopup
which can be overriden by providing \fILOCATION\fR.
