.TH DICTPOPUP\-CREATE 1

.SH SYNOPSIS
\fBdictpopup\-create\fR [\fIOPTION\fR]...

.SH DESCRIPTION
.B dictpopup\-create
parses Yomichan dictionary files to create a database used by
.BR dictpopup (1).

.SH OPTIONS
.TP
\fB\-i\fR \fIPATH\fR
Specify the directory containing the dictionaries to parse. The default is the current directory.
.TP
\fB\-d\fR \fIPATH\fR
Specify the directory where the database will be stored. The default is ~/.local/share/dictpopup.