name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        apt-get -qq update
        apt-get install -y -qq lmdb mecab
    - uses: actions/checkout@v4
    - name: make
      run: make
