name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y -qq liblmdb-dev mecab libgtk-3-dev libx11-dev
    - uses: actions/checkout@v4
    - name: make
      run: make
