name: Linux build

jobs:
  build_and_test:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - run: sudo apt-get update

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: gcc-10 clang clang-format clang-tidy cppcheck liblmdb-dev libmecab-dev libgtk-3-dev libx11-dev libcurl4-openssl-dev libnotify-dev libzip-dev
          version: 1.0

      - run: gcc --version

      - run: make clean analyse

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
  workflow_dispatch:
