name: Linux build

jobs:
  build_and_test:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - run: sudo apt-get update

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: gcc-10 clang clang-format clang-tidy cppcheck liblmdb-dev libmecab-dev libgtk-3-dev \
            libx11-dev libcurl4-openssl-dev libnotify-dev libzip-dev zipcmp zipmerge zipinfo ziptool
          version: 1.0

      - name: Download and install cgreen
        run: |
          wget https://github.com/cgreen-devs/cgreen/releases/download/1.6.3/cgreen-1.6.3-x86_64-linux.deb
          sudo dpkg -i cgreen-1.6.3-x86_64-linux.deb
          sudo apt install -f

      - run: gcc --version
      - run: clang-format --version

      - run: make analyse
      - run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
      - run: cmake --build build
      - run: ./build/run_tests

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
  workflow_dispatch:
