name: Linux build

on:
  push:
    paths:
      - 'src/**'
      - 'include/**'
    branches: [ "master" ]
  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
    branches: [ "master" ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y -qq liblmdb-dev libmecab-dev libgtk-3-dev libx11-dev libcurl4-openssl-dev libnotify-dev libzip-dev
    - uses: actions/checkout@v4
    - name: make
      run: make
